//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.StudentCourses = new HashSet<StudentCourses>();
            this.TeacherCourses = new HashSet<TeacherCourses>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long ClassId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<StudentCourses> StudentCourses { get; set; }
        public virtual ICollection<TeacherCourses> TeacherCourses { get; set; }
    }
}
