//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams
    {
        public long Id { get; set; }
        public decimal TheoryMarksTotal { get; set; }
        public decimal TheoryMarksObtained { get; set; }
        public Nullable<decimal> PracticalMarksTotal { get; set; }
        public Nullable<decimal> PracticalMarksObtained { get; set; }
        public decimal TotalMaxMarks { get; set; }
        public decimal TotalMarksObtained { get; set; }
        public System.DateTime LastDateModified { get; set; }
        public long StudentCourseId { get; set; }
    
        public virtual StudentCourses StudentCourses { get; set; }
    }
}
