//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentCourses = new HashSet<StudentCourses>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte[] Picture { get; set; }
        public string Guardian { get; set; }
        public string Relation { get; set; }
        public string Comments { get; set; }
        public long AddressId { get; set; }
        public long ClassId { get; set; }
        public string GuardianCNIC { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> IsArchive { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<StudentCourses> StudentCourses { get; set; }
    }
}
