//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourses
    {
        public StudentCourses()
        {
            this.Exams = new HashSet<Exams>();
            this.StudentAttendance = new HashSet<StudentAttendance>();
        }
    
        public long Id { get; set; }
        public long StudentId { get; set; }
        public long CourseId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Exams> Exams { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendance { get; set; }
    }
}
