//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAttendance
    {
        public long Id { get; set; }
        public long TeacherCourseId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public Nullable<bool> OnLeave { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> LastModifed { get; set; }
        public Nullable<bool> IsArchive { get; set; }
    
        public virtual TeacherCourses TeacherCourses { get; set; }
    }
}
