//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.TeacherCourses = new HashSet<TeacherCourses>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] Picture { get; set; }
        public string CNIC { get; set; }
        public string Comments { get; set; }
        public long AddressId { get; set; }
        public long ClassId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<TeacherCourses> TeacherCourses { get; set; }
    }
}
